# Generated by Django 6.0.5 on 2026-05-31 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_remove_vehicle_image_vehicleimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='created_at',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='cars/'),
        ),
    ]
