# Generated by Django 6.0.5 on 2026-06-10 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0003_remove_vehicle_created_at_vehicle_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='type_vehicule',
            field=models.CharField(choices=[('neuve', 'Voiture neuve'), ('moins3ans', 'Voiture moins de 3 ans'), ('occasion', "Voiture d'occasion")], default='moins3ans', max_length=20),
        ),
    ]
